### ISSUE TITLE
무슨 오류인가요

### ISSUE THREAD

**Issue by CordeliaDiv** [gdl-blue/imitated-seed-2#141]
undefined:52
                var data = await curs.execute("select aclgroup from aclgroup where username = ?", [ip_check(req]);
                                                                                                            ^^^

SyntaxError: missing ) after argument list
    at Object.<anonymous> (/root/wikiwiki/routes/router.js:29:45)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/root/wikiwiki/server.js:109:16)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)

**Comment by CordeliaDiv** [comment]
저걸 수정하니


(node:329796) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/root/wikiwiki/server.js:486
                aclgroupCache.css[item.name] = item.css;
                ^

ReferenceError: aclgroupCache is not defined
    at setWikiData (/root/wikiwiki/server.js:486:3)


이 오류가 뜹니다.
