### ISSUE TITLE
namuwiki-importer.js

### ISSUE THREAD

**Issue by dve1** [gdl-blue/imitated-seed-2#150]
namuwiki-importer.js에서 json 파일은 어떤 파일로 입력해야 하나요?

**Comment by dve1** [comment]
```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: Top-level object should be an array.
    at StreamArray._wait (/Users/alpha123/imitated-seed-2/node_modules/stream-json/streamers/StreamArray.js:24:23)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:556:12)
    at _write (node:internal/streams/writable:490:10)
    at Writable.write (node:internal/streams/writable:494:10)
    at Parser.ondata (node:internal/streams/readable:985:22)
    at Parser.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
    at Readable.push (node:internal/streams/readable:376:5)
Emitted 'error' event on Chain instance at:
    at StreamArray.<anonymous> (/Users/alpha123/imitated-seed-2/node_modules/stream-chain/index.js:146:71)
    at StreamArray.emit (node:events:526:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
오류가 납니다.

**Comment by dve1** [comment]
두 번째 댓글은 뭔가요?

**Comment by dve1** [comment]
어떤 화일을 사용해야 하나요?

**Comment by dve1** [comment]
화일을 찾을 수 없다고 나옵니다.

**Comment by dve1** [comment]
네
