### ISSUE TITLE
무슨 오류인가요

### ISSUE THREAD

**Issue by CordeliaDiv** [gdl-blue/imitated-seed-2#151]
/root/testwiki/node_modules/jsdom/lib/jsdom/browser/Window.js:238
  const windowInitialized = performance.now();
                            ^

ReferenceError: performance is not defined
    at new Window (/root/testwiki/node_modules/jsdom/lib/jsdom/browser/Window.js:238:29)
    at exports.createWindow (/root/testwiki/node_modules/jsdom/lib/jsdom/browser/Window.js:95:10)
    at new JSDOM (/root/testwiki/node_modules/jsdom/lib/api.js:36:20)
    at Object.<anonymous> (/root/testwiki/cemerick-jsdifflib.js:41:20)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)

추가로 파일 서버는 node fileserver 치면 바로 작동 가능한가요?

**Comment by CordeliaDiv** [comment]
저 친구를 해결하니 새로운 오류가 생겼습니다.


const { window } = new JSDOM();
                   ^

TypeError: JSDOM is not a constructor
    at Object.<anonymous> (/root/wikiwiki/cemerick-jsdifflib.js:41:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/wikiwiki/server.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by CordeliaDiv** [comment]
> 수정했습니다
> 
> 파일 서버는 node fileserver 필요 없이 그냥 내장했습니다. 바로 작동하며, 안 되면 config.json에서 disable_file_server를 true로 해주십시오 (자동 설정 되는데 만약 안 될 경우)

새롭게..

/root/testwiki/node_modules/jsdom/lib/api.js:140
          referrer: req.getHeader("referer") ?? undefined
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/testwiki/cemerick-jsdifflib.js:39:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

라는 오류가..

**Comment by CordeliaDiv** [comment]
하하;;;


node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/root/testwiki/node_modules/sqlite3/lib/binding/node-v93-linux-x64/node_sqlite3.node'
Require stack:
- /root/testwiki/node_modules/sqlite3/lib/sqlite3-binding.js
- /root/testwiki/node_modules/sqlite3/lib/sqlite3.js
- /root/testwiki/database.js
- /root/testwiki/functions.js
- /root/testwiki/routes/router.js
- /root/testwiki/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/root/testwiki/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/testwiki/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/root/testwiki/node_modules/sqlite3/lib/sqlite3.js',
    '/root/testwiki/database.js',
    '/root/testwiki/functions.js',
    '/root/testwiki/routes/router.js',
    '/root/testwiki/server.js'
  ]
}

**Comment by CordeliaDiv** [comment]
넵

**Comment by CordeliaDiv** [comment]
참고로 버전 Node 12 사용 중입니다 그 이상의 버전에는 npm i 시 오류가 생깁니다.

**Comment by CordeliaDiv** [comment]
정상 작동됩니다. 수고하셨습니다. 항상 노고에 감사드립니다. 좋은 하루되십시오!
