### ISSUE TITLE
작성하면 서버 터지는 문법

### ISSUE THREAD

**Issue by NOAH01112** [gdl-blue/imitated-seed-2#155]
{{{#!wiki style="display: none; display: @version2=block@;"
{{{#!wiki style="border: 1px solid gray; border-top: 5px solid gray; padding: 7px; margin-bottom: 0px;"
[[크리에이티브 커먼즈 라이선스|[[파일:ccl logo.svg|width=22.5px]]]] 이 @this=문서@의 내용 중 전체 또는 일부는 알파위키 {{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title@|@title@]]}}}{{{#!wiki style="display: n@external@ne"
{{{#!html <a href="https://alphawiki.org/w/@title@">@title@</a>}}}}}}}}} 문서의 [[https://www.alphawiki.org/w/@title@?rev=@version@&noredirect=1|r@version@]] 판{{{#!wiki style="display: inline; display: @paragraph=none@;"
, [[https://www.alphawiki.org/w/@title@?rev=@version@&noredirect=1#s-@paragraph@|@paragraph@번 문단]]}}}에서 가져왔습니다. [[https://www.alphawiki.org/history/@title@?from=@version@|이전 역사 보러 가기]]}}}}}}{{{#!wiki style="display: block; display: @version2=none@"
{{{#!wiki style="border: 1px solid gray; border-top: 5px solid gray; padding: 7px; margin-bottom: 0px;"
[[크리에이티브 커먼즈 라이선스|[[파일:ccl logo.svg|width=22.5px]]]] 이 @this=문서@의 내용 중 전체 또는 일부는 다른 문서에서 가져왔습니다.
{{{#!wiki style="text-align: center"
{{{#!folding [ 펼치기 · 접기 ]
{{{#!wiki style="text-align: left; padding: 0px 10px"
{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title@|@title@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title@?rev=@version@&noredirect=1|r@version@]] 판{{{#!wiki style="display: inline; display: @paragraph=none@;"
, [[https://www.alphawiki.org/w/@title@?rev=@version@&noredirect=1#s-@paragraph@|@paragraph@번 문단]]}}} ([[https://www.alphawiki.org/history/@title@?from=@version@|이전 역사]])
{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title2@|@title2@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title2@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title2@?rev=@version2@&noredirect=1|r@version2@]] 판{{{#!wiki style="display: inline; display: @paragraph2=none@;"
, [[https://www.alphawiki.org/w/@title2@?rev=@version2@&noredirect=1#s-@paragraph2@|@paragraph2@번 문단]]}}} ([[https://www.alphawiki.org/history/@title2@?from=@version2@|이전 역사]]){{{#!wiki style="display: block; display: @version3=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title3@|@title3@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title3@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title3@?rev=@version3@&noredirect=1|r@version3@]] 판{{{#!wiki style="display: inline; display: @paragraph3=none@;"
, [[https://www.alphawiki.org/w/@title3@?rev=@version3@&noredirect=1#s-@paragraph3@|@paragraph3@번 문단]]}}} ([[https://www.alphawiki.org/history/@title3@?from=@version3@|이전 역사]])}}}{{{#!wiki style="display: block; display: @version4=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title4@|@title4@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title4@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title4@?rev=@version4@&noredirect=1|r@version4@]] 판{{{#!wiki style="display: inline; display: @paragraph4=none@;"
, [[https://www.alphawiki.org/w/@title4@?rev=@version4@&noredirect=1#s-@paragraph4@|@paragraph4@번 문단]]}}} ([[https://www.alphawiki.org/history/@title4@?from=@version4@|이전 역사]])}}}{{{#!wiki style="display: block; display: @version5=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title5@|@title5@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title5@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title5@?rev=@version5@&noredirect=1|r@version5@]] 판{{{#!wiki style="display: inline; display: @paragraph5=none@;"
, [[https://www.alphawiki.org/w/@title5@?rev=@version5@&noredirect=1#s-@paragraph5@|@paragraph5@번 문단]]}}} ([[https://www.alphawiki.org/history/@title5@?from=@version5@|이전 역사]])}}}{{{#!wiki style="display: block; display: @version6=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title6@|@title6@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title6@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title6@?rev=@version6@&noredirect=1|r@version6@]] 판{{{#!wiki style="display: inline; display: @paragraph6=none@;"
, [[https://www.alphawiki.org/w/@title6@?rev=@version6@&noredirect=1#s-@paragraph6@|@paragraph6@번 문단]]}}} ([[https://www.alphawiki.org/history/@title6@?from=@version6@|이전 역사]])}}}{{{#!wiki style="display: block; display: @version7=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title7@|@title7@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title7@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title7@?rev=@version7@&noredirect=1|r@version7@]] 판{{{#!wiki style="display: inline; display: @paragraph7=none@;"
, [[https://www.alphawiki.org/w/@title7@?rev=@version7@&noredirect=1#s-@paragraph7@|@paragraph7@번 문단]]}}} ([[https://www.alphawiki.org/history/@title7@?from=@version7@|이전 역사]])}}}{{{#!wiki style="display: block; display: @version8=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title8@|@title8@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title8@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title8@?rev=@version8@&noredirect=1|r@version8@]] 판{{{#!wiki style="display: inline; display: @paragraph8=none@;"
, [[https://www.alphawiki.org/w/@title8@?rev=@version8@&noredirect=1#s-@paragraph8@|@paragraph8@번 문단]]}}} ([[https://www.alphawiki.org/history/@title8@?from=@version8@|이전 역사]])}}}{{{#!wiki style="display: block; display: @version9=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title9@|@title9@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title9@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title9@?rev=@version9@&noredirect=1|r@version9@]] 판{{{#!wiki style="display: inline; display: @paragraph9=none@;"
, [[https://www.alphawiki.org/w/@title9@?rev=@version9@&noredirect=1#s-@paragraph9@|@paragraph9@번 문단]]}}} ([[https://www.alphawiki.org/history/@title9@?from=@version9@|이전 역사]])}}}{{{#!wiki style="display: block; display: @version10=none@"

{{{#!wiki style="display: inline-block"
{{{#!wiki style="display: @external=none@"
[[https://www.alphawiki.org/w/@title10@|@title10@]]}}}{{{#!wiki style="display: n@external@ne"
[[@title10@]]}}}}}} 문서의 [[https://www.alphawiki.org/w/@title10@?rev=@version10@&noredirect=1|r@version10@]] 판{{{#!wiki style="display: inline; display: @paragraph10=none@;"
, [[https://www.alphawiki.org/w/@title10@?rev=@version10@&noredirect=1#s-@paragraph10@|@paragraph10@번 문단]]}}} ([[https://www.alphawiki.org/history/@title10@?from=@version10@|이전 역사]])}}}}}}}}}}}}}}}}}}
[[분류:파이위키]]

**Comment by NOAH01112** [comment]
이걸 로딩했는데 서버가 터지고
D:\20220904-backup\Documents\imitated-seed-2-master\namumark_parser.js:1179
                                        for(var attr of el.attributes) {
                                                           ^

TypeError: el.attributes is not iterable
    at markdown (D:\20220904-backup\Documents\imitated-seed-2-master\namumark_parser.js:1179:25)
    at async markdown (D:\20220904-backup\Documents\imitated-seed-2-master\namumark_parser.js:981:8)
    at async viewDocument (eval at <anonymous> (D:\20220904-backup\Documents\imitated-seed-2-master\routes\router.js:27:5), <anonymous>:78:20)

Node.js v20.10.0
에러가 뜹니다.

**Comment by NOAH01112** [comment]
감사합니다.
