### ISSUE TITLE
버그 수정

### ISSUE THREAD

**Issue by NOAH01112** [gdl-blue/imitated-seed-2#258]
스페이스바 눌러서 나오는 공백을 입력하면
node:_http_outgoing:652
    throw new ERR_HTTP_HEADERS_SENT('set');
          ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:652:11)
    at ServerResponse.header (D:\20220904-backup\Documents\imitated-seed-2-master\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (D:\20220904-backup\Documents\imitated-seed-2-master\node_modules\express\lib\response.js:174:12)
    at IncomingMessage.eval (eval at <anonymous> (D:\20220904-backup\Documents\imitated-seed-2-master\routes\router.js:27:5), <anonymous>:120:8) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v20.10.0
오류가 뜹니다

**Comment by wikiengine** [comment]
스페이스바를 어디에 입력하신건가요?

**Comment by NOAH01112** [comment]
![image](https://github.com/gdl-blue/imitated-seed-2/assets/93462843/ac1cbf1d-121f-49d4-b6e7-12b9c29d3bc1)
여기요

**Comment by NOAH01112** [comment]
근데 타 위키에서는 또 검색이 잘 되고 문서로 가기 누르면 대문으로 가지더라고요

**Comment by yoojinwoo12** [comment]
엔진은 최신버전인가요?

**Comment by NOAH01112** [comment]
네
