### ISSUE TITLE
이것도 node 버전을 낮춰야하는건가요

### ISSUE THREAD

**Issue by phonicsangel** [gdl-blue/imitated-seed-2#34]
goorm io에서 스킨을 buma로 바꾼 뒤..

(node:5514) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: no such table: config
--> in Database#all('select key, value from config', [], [Function (anonymous)])
    at /workspace/wikiwiki/imitated-seed-2/server.js:115:10
    at new Promise (<anonymous>)
    at Object.execute (/workspace/wikiwiki/imitated-seed-2/server.js:113:10)
    at setWikiData (/workspace/wikiwiki/imitated-seed-2/server.js:8325:24)
    at Object.<anonymous> (/workspace/wikiwiki/imitated-seed-2/server.js:8519:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled
with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

이렇게 됐는데 초기화를 해야하는지 모르겠습니다

**Comment by phonicsangel** [comment]
config.json 설정 다 완료하고 db 세팅까지 했는데 저럽니다

**Comment by JeonDohyeon** [comment]
node 12에서 초기화 후 진행해보세요. node 18에선 모듈 업데이트 없이는 실행되지 않는 터라..

**Comment by ontiger** [comment]
UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: no such table: config
--> in Database#all('select key, value from config', [], [Function (anonymous)])

config.json 및 wikidata.db 삭제(위키 초기화) 하십시오. DB가 제대로 꼬였습니다.
