### ISSUE TITLE
node server 치면 이런 오류가 뜨네요

### ISSUE THREAD

**Issue by angelmini** [gdl-blue/imitated-seed-2#49]
internal/modules/cjs/loader.js:1044
    throw err;
    ^

internal/modules/cjs/loader.js:1044
    throw err;
    ^

SyntaxError: /workspace/angelwiki/PeakyYura/config.json: Unexpected token : in JSON at position 81
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspace/angelwiki/PeakyYura/hostconfig.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)

**Comment by dupawiki** [comment]
config.json 내용을 올려보세요. 아마도 config.json에서 JSON 문법이 맞지 않는 듯 한데요...

**Comment by angelmini** [comment]
아 config.json에 한개 실수 한게 맞네요. 해결 했어요. 감사합니다
