### ISSUE TITLE
이건 무슨 오류인가요..?

### ISSUE THREAD

**Issue by angelmini** [gdl-blue/imitated-seed-2#54]
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at doListen (net.js:1413:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
Emitted 'error' event at:
    at emitErrorNT (net.js:1253:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)

**Comment by nawega** [comment]
이미 0.0.0.0:3000 에서 돌아가는 프로그램이 있다는 소립니다. 포트 충돌 또는 동시 실행을 확인하세요.
그리고 제발 **선검색후질문** 하세요.

**Comment by angelmini** [comment]
그런거요? 검색해도 나오지 않아 질문했던 것 입니다.

**Comment by gdl-blue** [comment]
같은 위키 서버를 동시에 두 번 실행하셨을 수도 있습니다
