### ISSUE TITLE
오류 문의

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#58]
더시드위키 theseeduser와 동일인 입니다.
namu-theseed liberty 스킨 그냥 넣으면 되는 줄 알았는데 찾아보니 static이 있어야 된다고 해서 유라위키 liberty 스킨 사용했습니다.
오류가 3가지 있는데 어떻게 해결해야 하는지 답변 부탁드립니다.

1. 사용자 차단 또는 aclgroup에 사용자를 추가한 내역이 있는 상태로 차단 내역을 클릭하면
undefined:99
                                ? (major == 4 && ver('4.0.20') ? `(${item.duration == '0' ? '영구적으로' : `${parses(item.duration)} 동안`})` : `${item.duration} 동안`)
                                   ^

ReferenceError: major is not defined
    at eval (eval at <anonymous> (D:\imitated-seed-2\routes\router.js:27:5), <anonymous>:99:8)
이렇게 오류가 발생하고, 엔진이 종료됩니다.

2. 라이선스 탭 클릭하면

undefined:4
                <p>(the seed v${major}.${minor}.${revision})</p>
                                ^

ReferenceError: major is not defined
    at eval (eval at <anonymous> (D:\imitated-seed-2\routes\router.js:27:5), <anonymous>:4:19)
    at Layer.handle [as handle_request] (D:\imitated-seed-2\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\imitated-seed-2\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\imitated-seed-2\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\imitated-seed-2\node_modules\express\lib\router\layer.js:95:5)
    at D:\imitated-seed-2\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\imitated-seed-2\node_modules\express\lib\router\index.js:346:12)
    at next (D:\imitated-seed-2\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\imitated-seed-2\node_modules\express\lib\router\index.js:175:3)
    at router (D:\imitated-seed-2\node_modules\express\lib\router\index.js:47:12)

이렇게 나오고 역시 엔진이 종료됩니다.

3. glitch에서 엔진을 실행하면 이미 0.0.0.0:3000이 사용 중이라는데 이 포트에 사용중인 프로그램을 종료해도 같은 문제가 일어납니다.

**Comment by roselia2023** [comment]
해당 문제는 엔진 문제라기 보단 위키 스킨 문제인 듯 하네요.

**Comment by roselia2023** [comment]
스킨 수정하였어요. 해당 이슈는 닫으셔도 될 것 같습니다 [Liberty 수정 버전](https://github.com/COVERTIV/Liberty-skin)

**Comment by roselia2023** [comment]
glitch는 refresh로 새로고침하는게 제일 편하실 겁니다.

**Comment by gdl-blue** [comment]
수정 완료
