### ISSUE TITLE
테스트 서버 복구 방법 알려주세요.

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#60]
글리치에서 db를 잘못 건드려서

app@mire-satin-bass:~ 03:45 
$ node server
node-pre-gyp info This Node instance does not support builds for Node-API version 6
node-pre-gyp info This Node instance does not support builds for Node-API version 6
[경고!]: 시스템이 멀티 쓰레딩을 지원하지 않습니다
(node:20672) UnhandledPromiseRejectionWarning: Error: SQLITE_CORRUPT: database disk image is malformed
--> in Database#all('select key, value from config', [], [Function])
    at /app/database.js:9:10
    at new Promise (<anonymous>)
    at Object.execute (/app/database.js:7:10)
    at setWikiData (/app/server.js:284:24)
    at Object.<anonymous> (/app/server.js:479:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
(node:20672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

이렇게 되었는데 어디를 수정해야 되는지요?

**Comment by theseeduser** [comment]
오류가 또 발생해서 새로 열어야겠습니다.
