### ISSUE TITLE
회원가입 오류

### ISSUE THREAD

**Issue by Roselia31** [gdl-blue/imitated-seed-2#89]
회원가입을 할려고 하면 아래와 같은 오류가 뜨며 회원가입이 안됩니다.

(node:578326) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: table users has no column named email
--> in Database#run('insert into users (username, password, email) values (?, ?, ?)', [
  'Rose',
  'ip',
  'angelwiki.help@gmail.com'
], [Function])
    at /root/dreamseed/database.js:14:10
    at new Promise (<anonymous>)
    at Object.execute (/root/dreamseed/database.js:7:10)
    at signupScreen (eval at <anonymous> (/root/dreamseed/routes/router.js:29:5), <anonymous>:242:14)
(node:578326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:578326) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 24fw** [comment]
이메일이 에러가 좀 많네요

**Comment by Roselia31** [comment]
저건 이메일을 안쓰는 테스트위키에서 발견 후 제 localhost에서 코드를 가져온거라 이메일하고 크게 연관은 없을뜻 합니다

**Comment by 24fw** [comment]
혹시 db가 이메일업데이트전에 생성된 db인가요?

**Comment by Roselia31** [comment]
네 그전에 생성된 데이터베이스입니다.

**Comment by 24fw** [comment]
users에 email을 저장해서 db구조가 바뀌었습니다.

**Comment by 24fw** [comment]
users에 email열을 추가하시거나 db를 새로만드시면 해결될겁니다.

**Comment by Roselia31** [comment]
DB를 새로 만들면 내용이 다 날라가서 혹시 어떻게 추가하나요? 제가 코딩에 대한 지식이 별로 없어서

**Comment by 24fw** [comment]
https://bskyvision.com/entry/sqlite3-%EA%B8%B0%EC%A1%B4-%ED%85%8C%EC%9D%B4%EB%B8%94%EC%97%90-%EC%BB%AC%EB%9F%BC%EC%97%B4-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0 이거 참고해보시면 될것같습니다.

**Comment by Roselia31** [comment]
음 어떻게 하는건지 이해가 안가는 군요..

**Comment by 24fw** [comment]
나중에 시간나면 칼럼추가 프로그램 만들어야겠군요

**Comment by Roselia31** [comment]
근데 혹시 DB에 접속 이렇게 하는게 아닌가요..?
PS C:\Users\user\Desktop\imitatedseed> sqlite3 wikidata.db
sqlite3 : 'sqlite3' 용어가 cmdlet, 함수, 스크립트 파일 또는 실행할 수 있는 프로그램 이름으로 인식되지 않습니다. 이름이 정확한지 확인하고 경로가 포함된 경우 경로가 올바른지 검증한 다음 다시 시도하십
시오.
위치 줄:1 문자:1
+ sqlite3 wikidata.db
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sqlite3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by 24fw** [comment]
sqlite3 설치 하셨나요? (npm말고)

**Comment by Roselia31** [comment]
sqlite> .schema users
CREATE TABLE users ( username TEXT DEFAULT '', password TEXT DEFAULT '');
이렇게 하는게 맞는지 확인 부탁드립니다. DB가 잘못 만지면 다 날라가다 보니.. 하하..

**Comment by Roselia31** [comment]
sqlite> ALTER TABLE users ADD COLUMN email
확실히 이렇게 하는게 아닌가 보군요
