### ISSUE TITLE
이건 무슨 오류인가요?

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#98]
위키 운영하기 좋은 호스팅 업체 있어서 설치해 봤는데 최초 실행 시에는 문제가 없지만 조금 뒤에 다시 실행해보면 이런 오류가 뜹니다. 호스팅은 replit.com 입니다.

~/testwiki/imitated-seed-2$ node server
[경고!]: 시스템이 멀티 쓰레딩을 지원하지 않습니다
0.0.0.0:3000에서 실행 중. . .
/home/runner/testwiki/imitated-seed-2/server.js:170
    if(req.session.username) {
                   ^

TypeError: Cannot read properties of undefined (reading 'username')
    at /home/runner/testwiki/imitated-seed-2/server.js:170:17
    at Layer.handle [as handle_request] (/home/runner/testwiki/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:144:13)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:140:7)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:140:7)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:140:7)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:140:7)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:140:7)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:140:7)
    at next (/home/runner/testwiki/node_modules/express/lib/router/route.js:140:7)

Node.js v18.12.1

**Comment by theseeduser** [comment]
npm i 실행 후 다시 해보니 되네요

**Comment by theseeduser** [comment]
이번에는 npm으로도 오류가 해결되지 않네요.

**Comment by theseeduser** [comment]
지금은 Run 기능으로 해결했습니다.

**Comment by theseeduser** [comment]
오류가 나왔다가 안나왔다가 반복되서 열어놓겠습니다.

**Comment by kepitrion** [comment]
node 버전을 내려보세요. nvm 이용하시면 쉽게 가능합니다. Node 18이면 권장 버전보다 많이 높습니다.

**Comment by theseeduser** [comment]
nvm 설치가 안 되네요

**Comment by kepitrion** [comment]
apt나 yarn 사용해서 node를 완전히 삭제 후 재설치 해 보세요.

**Comment by theseeduser** [comment]
코드 지우기를 통해 완전히 해결된 것 같아서 닫겠습니다.
